### ISSUE TITLE
ARGS doesn't work

### ISSUE THREAD

**Issue by vvjn** [JuliaComputing/static-julia#48]
The following program
```
module Hello

Base.@ccallable function julia_main(ARGS::Vector{String})::Cint
    println(length(ARGS))
    return 0
end

end
```

always prints 0, whether I run `./hello` or `./hello 1 2 3`, etc.

**Comment by phlavenk** [comment]
You have to cope with the argument passing into your julia function in the program.c file yourself - the juliac script is not generating the "glue" program.c file, that's for now the manual task for programmer. Look into the `program2.c` file to see what to do in order to convert arguments of the main / wmain  function and pass them to the julia function.

**Comment by vvjn** [comment]
Thanks! Using `program2.c` works very well, so I'm closing this.
